In [114]:
'''import dash
from plotly import graph_objs
from dash_bootstrap_templates import load_figure_template
import dash_bootstrap_components as dbc
from dash import Input, Output, State, dcc, html
from dash_bootstrap_components._components.Navbar import Navbar
import plotly.express as px'''
import pandas as pd
import math

In [115]:

millnames = ['',' Mille',' Million',' Milliard',' Mille milliards']

def millify(n):
    n = float(n)
    millidx = max(0,min(len(millnames)-1,
                        int(math.floor(0 if n == 0 else math.log10(abs(n))/3))))

    return '{:.0f}{}'.format(n / 10**(3 * millidx), millnames[millidx])

In [116]:
### importing Data and extracting 
Export_total = pd.read_csv('data/Export_total.csv')
Export_total.head(1)

,Libellé du groupement d'utilisation,Libellé de la section CTCI,Libellé de la division CTCI,Libellé du groupe CTCI,Continent,Libellé du pays,Libellé du flux,Total dh
0,"ALIMENTATION, BOISSONS ET TABACS",PRODUITS ALIMENTAIRES ET ANIMAUX VIVANTS,LÉGUMES ET FRUITS,"FRUITS, MÊME À COQUE (À L¿EXCLUSION DES FRUITS...",AFRIQUE,CONGO,Exportations FAB,1007201.5

In [117]:
new_df = pd.read_csv('data/new_df.csv')
new_df.head()

,Libellé du pays,Libellé du flux,Valeur DHS Janvier 2018,Valeur DHS Février 2018,Valeur DHS Mars 2018,Valeur DHS Avril 2018,Valeur DHS Mai 2018,Valeur DHS Juin 2018,Valeur DHS Juillet 2018,Valeur DHS Aout 2018,...,Valeur DHS Septembre 2020,Valeur DHS Octobre 2020,Valeur DHS Novembre 2020,Valeur DHS Décembre 2020,Valeur DHS Janvier 2021,Valeur DHS Février 2021,Valeur DHS Mars 2021,Valeur DHS Avril 2021,Valeur DHS Mai 2021,Valeur DHS Juin 2021
0,CONGO,Exportations FAB,70020.000,168350.000,0.000,0.0,0.000,0.0,0.0,0.0,...,0.0,0.0,96200.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0
1,NIGERIA,Exportations FAB,425387.000,161192.500,0.000,62437.5,0.000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000,652186.000,1176807.8,192400.0,0.0,0.0,0.0
2,KAZAKHSTAN,Exportations FAB,108225.000,0.000,0.000,0.0,0.000,0.0,0.0,0.0,...,0.0,275664.0,1321247.0,168350.000,288363.000,0.0,245592.0,0.0,0.0,0.0
3,ITALIE,Exportations FAB,5636520.434,2573814.994,852133.806,0.0,2633496.431,0.0,178650.0,377795.0,...,0.0,0.0,0.0,1872443.446,7238766.578,0.0,0.0,0.0,1056352.0,2.0
4,CANADA,Exportations FAB,0.000,0.000,0.000,0.0,36393.000,0.0,0.0,0.0,...,18979.0,15273.0,0.0,0.000,0.000,121193.0,0.0,0.0,0.0,0.0

In [118]:
flux=new_df.groupby(['Libellé du pays','Libellé du flux']).sum()
flux=flux.transpose()
flux.set_index(pd.date_range(start='2018-01-01', periods=42,freq='M'),inplace=True)
flux.head()

Libellé du pays      AFGHANISTAN                   \
Libellé du flux Exportations FAB Importations CAF
2018-01-31                   0.0              0.0
2018-02-28                   0.0              0.0
2018-03-31             1075705.0              0.0
2018-04-30                   0.0              0.0
2018-05-31                   0.0          25371.0

Libellé du pays                                                                                  \
Libellé du flux Importations en admission temporaire pour perfectionnement actif  avec paiement
2018-01-31                                                     0.0
2018-02-28                                                     0.0
2018-03-31                                                     0.0
2018-04-30                                                     0.0
2018-05-31                                                     0.0

Libellé du pays                                                                                  \
Libellé du flux Importations en admission temporaire pour perfectionnement actif  sans paiement
2018-01-31                                                     0.0
2018-02-28                                                     0.0
2018-03-31                                                     0.0
2018-04-30                                                     0.0
2018-05-31                                                     0.0

Libellé du pays                                                                                           \
Libellé du flux Réexportations en suite d'admission temporaire pour perfectionnement actif avec paiement
2018-01-31                                                     0.0
2018-02-28                                                     0.0
2018-03-31                                                819385.0
2018-04-30                                                     0.0
2018-05-31                                                     0.0

Libellé du pays   AFRIQUE DU SUD                   \
Libellé du flux Exportations FAB Importations CAF
2018-01-31          2.963012e+07     1.143497e+08
2018-02-28          2.168777e+07     1.778038e+08
2018-03-31          3.342333e+07     3.289373e+07
2018-04-30          2.078962e+07     5.505742e+07
2018-05-31          4.081473e+07     4.519970e+07

Libellé du pays                                                                                  \
Libellé du flux Importations en admission temporaire pour perfectionnement actif  avec paiement
2018-01-31                                               2203468.0
2018-02-28                                              52803495.0
2018-03-31                                              24985665.0
2018-04-30                                              30476224.0
2018-05-31                                              25647291.0

Libellé du pays                                                                                  \
Libellé du flux Importations en admission temporaire pour perfectionnement actif  sans paiement
2018-01-31                                                199456.0
2018-02-28                                                 68023.0
2018-03-31                                                250694.0
2018-04-30                                                585773.0
2018-05-31                                                484073.0

Libellé du pays                                                                                           \
Libellé du flux Réexportations en suite d'admission temporaire pour perfectionnement actif avec paiement
2018-01-31                                             7816646.000
2018-02-28                                             3386914.600
2018-03-31                                             6107447.105
2018-04-30                                             7242430.000
2018-05-31                                             5504645.730

Libellé du pays  ...  \
Libellé du flux  ...
2018-01-31       ...
2018-02-28       ...
2018-03-31       ...
2018-04-30       ...
2018-05-31       ...

Libellé du pays                                                                                    YEMEN  \
Libellé du flux Réexportations en suite d'admission temporaire pour perfectionnement actif sans paiement
2018-01-31                                                     0.0
2018-02-28                                                     0.0
2018-03-31                                                     0.0
2018-04-30                                                     0.0
2018-05-31                                                     0.0

Libellé du pays     YOUGOUSLAVIE                            ZAMBIE  \
Libellé du flux Exportations FAB Importations CAF Exportations FAB
2018-01-31                   0.0              0.0              0.0
2018-02-28                   0.0              0.0              0.0
2018-03-31                   0.0              0.0          53412.0
2018-04-30                   0.0           5011.0          84380.0
2018-05-31                   0.0           1000.0              0.0

Libellé du pays                   \
Libellé du flux Importations CAF
2018-01-31             1413261.0
2018-02-28                   0.0
2018-03-31             6808168.0
2018-04-30                   0.0
2018-05-31                6521.0

Libellé du pays                                                                                  \
Libellé du flux Importations en admission temporaire pour perfectionnement actif  avec paiement
2018-01-31                                                     0.0
2018-02-28                                                     0.0
2018-03-31                                               6808168.0
2018-04-30                                                     0.0
2018-05-31                                                     0.0

Libellé du pays                                                                                           \
Libellé du flux Réexportations en suite d'admission temporaire pour perfectionnement actif avec paiement
2018-01-31                                                     0.0
2018-02-28                                                     0.0
2018-03-31                                                     0.0
2018-04-30                                                     0.0
2018-05-31                                                     0.0

Libellé du pays         ZIMBABWE                   \
Libellé du flux Exportations FAB Importations CAF
2018-01-31                   0.0             21.0
2018-02-28                   0.0              0.0
2018-03-31              378119.0              0.0
2018-04-30                   0.0              0.0
2018-05-31                   0.0          58003.0

Libellé du pays
Libellé du flux Importations en admission temporaire pour perfectionnement actif  avec paiement
2018-01-31                                                     0.0
2018-02-28                                                     0.0
2018-03-31                                                     0.0
2018-04-30                                                     0.0
2018-05-31                                                     0.0

[5 rows x 985 columns]

In [119]:
pays_et_utilisation = Export_total.groupby(['Libellé du pays',"Libellé du groupement d'utilisation"]).sum()
flux_et_utilisation = Export_total.groupby(['Libellé du flux',"Libellé du groupement d'utilisation"]).sum()
division = Export_total.groupby(["Libellé de la division CTCI"]).sum().sort_values('Total dh', ascending=False)
continent_et_utilisation = Export_total.groupby(["Continent","Libellé du groupement d'utilisation"]).sum()

### Les catégories des produits les plus importés

In [120]:
utilisation_import=Export_total[(Export_total["Libellé du flux"]=="Importations CAF")].groupby(["Libellé du groupement d'utilisation"]).sum().sort_values('Total dh', ascending=False)
utilisation_import

                                                  Total dh
Libellé du groupement d'utilisation
PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL        4.107154e+11
PRODUITS FINIS DE CONSOMMATION                3.769233e+11
DEMI  PRODUITS                                3.534150e+11
ENERGIE  ET  LUBRIFIANTS                      2.403281e+11
ALIMENTATION, BOISSONS ET TABACS              1.809376e+11
PRODUITS BRUTS D'ORIGINE ANIMALE ET VEGETALE  4.544973e+10
PRODUITS BRUTS D'ORIGINE MINERALE             3.395411e+10
PRODUITS FINIS D'EQUIPEMENT AGRICOLE          6.425468e+09
OR INDUSTRIEL                                 5.861206e+08

### Les catégories des produits les plus exportés

In [121]:
utilisation_export=Export_total[(Export_total["Libellé du flux"]=="Exportations FAB")].groupby(["Libellé du groupement d'utilisation"]).sum().sort_values('Total dh', ascending=False)
utilisation_export

                                                  Total dh
Libellé du groupement d'utilisation
PRODUITS FINIS DE CONSOMMATION                2.874920e+11
DEMI  PRODUITS                                2.138336e+11
ALIMENTATION, BOISSONS ET TABACS              1.998778e+11
PRODUITS FINIS D'EQUIPEMENT INDUSTRIEL        1.955631e+11
PRODUITS BRUTS D'ORIGINE MINERALE             4.726345e+10
PRODUITS BRUTS D'ORIGINE ANIMALE ET VEGETALE  2.058247e+10
ENERGIE  ET  LUBRIFIANTS                      9.379041e+09
OR INDUSTRIEL                                 1.614490e+09
PRODUITS FINIS D'EQUIPEMENT AGRICOLE          4.900290e+08

### Les plus grands exportateurs

In [122]:
Export_total[(Export_total["Libellé du flux"]=="Exportations FAB")].groupby(["Libellé du pays"]).sum().sort_values('Total dh', ascending=False)

                                           Total dh
Libellé du pays
ESPAGNE                                2.322271e+11
FRANCE                                 2.138473e+11
ITALIE                                 4.282756e+10
ETATS-UNIS                             3.799372e+10
INDE                                   3.544411e+10
...                                             ...
SAINT-MARIN                            6.476500e+04
REPUBLIQUE DEMOCRATIQUE POPULAIRE LAO  4.800000e+04
GUERNESEY                              2.968900e+04
ILES MARSHALL                          2.481219e+04
SAINT-MARTIN (PARTIE NEERLANDAISE)     2.800000e+02

[207 rows x 1 columns]

### Les plus grands importateurs

In [123]:
Export_total[(Export_total["Libellé du flux"]=="Importations CAF")].groupby(["Libellé du pays"]).sum().sort_values('Total dh', ascending=False)

                                                  Total dh
Libellé du pays
ESPAGNE                                       2.577609e+11
FRANCE                                        1.961763e+11
CHINE                                         1.774249e+11
ETATS-UNIS                                    1.172501e+11
ITALIE                                        8.922057e+10
...                                                    ...
ILES MINEURES ELOIGNEES DES ETATS-UNIS        2.239000e+03
ILES CAIMANES                                 1.505000e+03
SAINTE-HELENE, ASCENSION ET TRISTAN DA CUNHA  1.460000e+03
ETATS FEDERES DE MICRONESIE                   1.052000e+03
TERRITOIRE BRITANNIQUE DE L'OCEAN INDIEN      2.000000e+00

[214 rows x 1 columns]

### Continents de plus grande importations

In [124]:
Export_total[(Export_total["Libellé du flux"]=="Exportations FAB")].groupby(["Continent"]).sum().sort_values('Total dh', ascending=False)

               Total dh
Continent
EUROPE     6.873717e+11
ASIE       9.723499e+10
AMERIQUE   9.704009e+10
AFRIQUE    7.800902e+10
AUTRE      1.427801e+10
AUSTRALIE  2.162062e+09

### Continents de plus grande exportations

In [125]:
Export_total[(Export_total["Libellé du flux"]=="Importations CAF")].groupby(["Continent"]).sum().sort_values('Total dh', ascending=False)

               Total dh
Continent
EUROPE     1.045050e+12
ASIE       3.438313e+11
AMERIQUE   1.931039e+11
AFRIQUE    5.993265e+10
AUTRE      4.488825e+09
AUSTRALIE  2.328250e+09

In [126]:
annual=pd.read_csv('data/Annual.csv',sep=';',decimal=',')
annual.head()

,Code du pays,Libellé du pays,Code du flux,Libellé du flux,Valeur DHS 2010,Valeur DHS 2011,Valeur DHS 2012,Valeur DHS 2013,Valeur DHS 2014,Valeur DHS 2015,Valeur DHS 2016,Valeur DHS 2017,Valeur DHS 2018,Valeur DHS 2019,Valeur DHS 2020,Valeur DHS 2021,Unnamed: 16
0,NaN,NaN,141,Importations en admission temporaire pour perf...,0,0.0,0.000,0.000,0.00,0.000,0.000,4.000,0.000,0.000,0.000,0.000,NaN
1,NaN,NaN,14,Importations CAF,0,0.0,0.000,0.000,0.00,0.000,0.000,5.000,0.000,0.000,0.000,0.000,NaN
2,AD,ANDORRE,24,Exportations FAB,17000,0.0,1132030.866,3086862.405,6370835.38,7754181.694,7308319.716,5987804.994,6375642.244,6127175.242,3778609.465,605967.931,NaN
3,AD,ANDORRE,241,Réexportations en suite d'admission temporaire...,0,0.0,0.000,2324293.765,5544210.38,7337091.984,7308319.716,5987804.994,6340370.244,6127175.242,3736763.555,605967.931,NaN
4,AD,ANDORRE,242,Réexportations en suite d'admission temporaire...,0,0.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,41845.910,0.000,NaN

In [127]:
annual.drop(['Unnamed: 16','Valeur DHS 2021'],1,inplace=True)
annual.head()

,Code du pays,Libellé du pays,Code du flux,Libellé du flux,Valeur DHS 2010,Valeur DHS 2011,Valeur DHS 2012,Valeur DHS 2013,Valeur DHS 2014,Valeur DHS 2015,Valeur DHS 2016,Valeur DHS 2017,Valeur DHS 2018,Valeur DHS 2019,Valeur DHS 2020
0,NaN,NaN,141,Importations en admission temporaire pour perf...,0,0.0,0.000,0.000,0.00,0.000,0.000,4.000,0.000,0.000,0.000
1,NaN,NaN,14,Importations CAF,0,0.0,0.000,0.000,0.00,0.000,0.000,5.000,0.000,0.000,0.000
2,AD,ANDORRE,24,Exportations FAB,17000,0.0,1132030.866,3086862.405,6370835.38,7754181.694,7308319.716,5987804.994,6375642.244,6127175.242,3778609.465
3,AD,ANDORRE,241,Réexportations en suite d'admission temporaire...,0,0.0,0.000,2324293.765,5544210.38,7337091.984,7308319.716,5987804.994,6340370.244,6127175.242,3736763.555
4,AD,ANDORRE,242,Réexportations en suite d'admission temporaire...,0,0.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,41845.910

In [145]:
annual.isnull().sum()

Code du pays        8
Libellé du pays     2
Code du flux        0
Libellé du flux     0
Valeur DHS 2010     0
Valeur DHS 2011     3
Valeur DHS 2012     0
Valeur DHS 2013    18
Valeur DHS 2014     0
Valeur DHS 2015     0
Valeur DHS 2016     0
Valeur DHS 2017     0
Valeur DHS 2018     0
Valeur DHS 2019     0
Valeur DHS 2020     0
dtype: int64

In [149]:
annual.drop(0, inplace=True)
annual.drop(1, inplace=True)

In [146]:
 for i in annual[annual['Valeur DHS 2011'].isnull()].index.tolist():print(annual.iloc[[i]])

    Code du pays Libellé du pays  Code du flux  \
171           BW        BOTSWANA           242

                                       Libellé du flux  Valeur DHS 2010  \
171  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
171              NaN              0.0              0.0              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
171              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
171              0.0              0.0
     Code du pays Libellé du pays  Code du flux  \
1102           TJ     TADJIKISTAN           242

                                        Libellé du flux  Valeur DHS 2010  \
1102  Réexportations en suite d'admission temporaire...                0

      Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
1102              NaN              0.0              0.0              0.0

      Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
1102              0.0              0.0              0.0              0.0

      Valeur DHS 2019  Valeur DHS 2020
1102              0.0              0.0
     Code du pays                  Libellé du pays  Code du flux  \
1192           VC  SAINT-VINCENT-ET-LES GRENADINES           242

                                        Libellé du flux  Valeur DHS 2010  \
1192  Réexportations en suite d'admission temporaire...                0

      Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
1192              NaN              0.0              0.0              0.0

      Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
1192              0.0              0.0              0.0              0.0

      Valeur DHS 2019  Valeur DHS 2020
1192              0.0              0.0

In [143]:
for i in annual[annual['Valeur DHS 2013'].isnull()].index.tolist():print(annual.iloc[[i]])

   Code du pays Libellé du pays  Code du flux  \
14           AF     AFGHANISTAN           242

                                      Libellé du flux  Valeur DHS 2010  \
14  Réexportations en suite d'admission temporaire...                0

    Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
14              0.0              0.0              NaN              0.0

    Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
14              0.0              0.0              0.0              0.0

    Valeur DHS 2019  Valeur DHS 2020
14              0.0              0.0
   Code du pays Libellé du pays  Code du flux  \
81           AW           ARUBA           242

                                      Libellé du flux  Valeur DHS 2010  \
81  Réexportations en suite d'admission temporaire...                0

    Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
81              0.0              0.0              NaN              0.0

    Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
81              0.0              0.0              0.0              0.0

    Valeur DHS 2019  Valeur DHS 2020
81              0.0              0.0
    Code du pays Libellé du pays  Code du flux  \
141           BM        BERMUDES           241

                                       Libellé du flux  Valeur DHS 2010  \
141  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
141              0.0              0.0              NaN              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
141              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
141              0.0              0.0
    Code du pays Libellé du pays  Code du flux  \
144           BM        BERMUDES           242

                                       Libellé du flux  Valeur DHS 2010  \
144  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
144              0.0              0.0              NaN              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
144              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
144              0.0              0.0
    Code du pays Libellé du pays  Code du flux  \
165           BS         BAHAMAS           242

                                       Libellé du flux  Valeur DHS 2010  \
165  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
165              0.0              0.0              NaN              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
165              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
165              0.0              0.0
    Code du pays Libellé du pays  Code du flux  \
360           FJ           FIDJI           242

                                       Libellé du flux  Valeur DHS 2010  \
360  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
360              0.0              0.0              NaN              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
360              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
360              0.0              0.0
    Code du pays Libellé du pays  Code du flux  \
361           FJ           FIDJI           241

                                       Libellé du flux  Valeur DHS 2010  \
361  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
361              0.0              0.0              NaN              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
361              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
361              0.0              0.0
    Code du pays Libellé du pays  Code du flux  \
554           JE          JERSEY           241

                                       Libellé du flux  Valeur DHS 2010  \
554  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
554              0.0              0.0              NaN              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
554              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
554              0.0              0.0
    Code du pays Libellé du pays  Code du flux  \
561           JM        JAMAIQUE           242

                                       Libellé du flux  Valeur DHS 2010  \
561  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
561              0.0              0.0              NaN              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
561              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
561              0.0              0.0
    Code du pays       Libellé du pays  Code du flux  \
600           KN  SAINT-KITTS-ET-NEVIS           242

                                       Libellé du flux  Valeur DHS 2010  \
600  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
600              0.0              0.0              NaN              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
600              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
600              0.0              0.0
    Code du pays       Libellé du pays  Code du flux  \
602           KN  SAINT-KITTS-ET-NEVIS           241

                                       Libellé du flux  Valeur DHS 2010  \
602  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
602              0.0              0.0              NaN              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
602              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
602              0.0              0.0
    Code du pays                        Libellé du pays  Code du flux  \
634           LA  REPUBLIQUE DEMOCRATIQUE POPULAIRE LAO           242

                                       Libellé du flux  Valeur DHS 2010  \
634  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
634              0.0              0.0              NaN              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
634              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
634              0.0              0.0
    Code du pays Libellé du pays  Code du flux  \
726           MH   ILES MARSHALL           241

                                       Libellé du flux  Valeur DHS 2010  \
726  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
726              0.0              0.0              NaN              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
726              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
726              0.0              0.0
    Code du pays Libellé du pays  Code du flux  \
727           MH   ILES MARSHALL           242

                                       Libellé du flux  Valeur DHS 2010  \
727  Réexportations en suite d'admission temporaire...                0

     Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
727              0.0              0.0              NaN              0.0

     Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
727              0.0              0.0              0.0              0.0

     Valeur DHS 2019  Valeur DHS 2020
727              0.0              0.0
     Code du pays Libellé du pays  Code du flux  \
1036           SM     SAINT-MARIN           241

                                        Libellé du flux  Valeur DHS 2010  \
1036  Réexportations en suite d'admission temporaire...                0

      Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
1036              0.0              0.0              NaN              0.0

      Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
1036              0.0              0.0              0.0              0.0

      Valeur DHS 2019  Valeur DHS 2020
1036              0.0              0.0
     Code du pays Libellé du pays  Code du flux  \
1211           VU         VANUATU           241

                                        Libellé du flux  Valeur DHS 2010  \
1211  Réexportations en suite d'admission temporaire...                0

      Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
1211              0.0              0.0              NaN              0.0

      Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
1211              0.0              0.0              0.0              0.0

      Valeur DHS 2019  Valeur DHS 2020
1211              0.0              0.0
     Code du pays Libellé du pays  Code du flux  \
1212           VU         VANUATU           242

                                        Libellé du flux  Valeur DHS 2010  \
1212  Réexportations en suite d'admission temporaire...                0

      Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
1212              0.0              0.0              NaN              0.0

      Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
1212              0.0              0.0              0.0              0.0

      Valeur DHS 2019  Valeur DHS 2020
1212              0.0              0.0
     Code du pays Libellé du pays  Code du flux  \
1221           XK          KOSOVO           242

                                        Libellé du flux  Valeur DHS 2010  \
1221  Réexportations en suite d'admission temporaire...                0

      Valeur DHS 2011  Valeur DHS 2012  Valeur DHS 2013  Valeur DHS 2014  \
1221              0.0              0.0              NaN              0.0

      Valeur DHS 2015  Valeur DHS 2016  Valeur DHS 2017  Valeur DHS 2018  \
1221              0.0              0.0              0.0              0.0

      Valeur DHS 2019  Valeur DHS 2020
1221              0.0              0.0

In [151]:
annual.fillna(0).isnull().sum()

Code du pays       0
Libellé du pays    0
Code du flux       0
Libellé du flux    0
Valeur DHS 2010    0
Valeur DHS 2011    0
Valeur DHS 2012    0
Valeur DHS 2013    0
Valeur DHS 2014    0
Valeur DHS 2015    0
Valeur DHS 2016    0
Valeur DHS 2017    0
Valeur DHS 2018    0
Valeur DHS 2019    0
Valeur DHS 2020    0
dtype: int64